"""Build NUMBERS.md: every number the paper may use, with its label, source file and producing SHA.

The paper takes numbers only from this table. Each row has a stable id (section-row). Values are copied
from result files, never retyped. Intervals are 95% unless the column says otherwise.
"""
import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from th import config  # noqa: E402

R = config.RESULTS
PKG = config.PKG


def read_csv(p):
    sha = ""
    lines = []
    with open(p) as fh:
        for l in fh:
            if l.startswith("#"):
                if "git_sha=" in l:
                    sha = l.split("git_sha=")[1].split(";")[0].split()[0]
                continue
            lines.append(l)
    rows = list(csv.DictReader(lines))
    for k in ("git_sha", "sha"):
        if not sha and rows and rows[0].get(k):
            sha = rows[0][k]
    return rows, sha


def fmt(v):
    if v is None or v == "":
        return ""
    try:
        f = float(v)
    except (TypeError, ValueError):
        return str(v)
    if f != f:
        return "nan"
    if f == int(f) and abs(f) < 1e6 and "." not in str(v):
        return str(int(f))
    a = abs(f)
    if a != 0 and (a < 1e-3 or a >= 1e5):
        return f"{f:.3e}"
    return f"{f:.4f}"


SECTIONS = []


class NumbersError(RuntimeError):
    pass


def ci(lo, hi):
    f = lambda r: f"[{fmt(r.get(lo))}, {fmt(r.get(hi))}]" if r.get(lo) not in (None, "") else ""
    f.needs = (lo, hi)
    return f


def table(out, sec, title, path, cols, rows, sha, where=None, label_col="label", note=""):
    """Amendment 1 (A11): a duplicate section code, an empty table, or a requested column absent from the source
    file raises NumbersError instead of silently yielding blanks or picking one occurrence."""
    if sec in SECTIONS:
        raise NumbersError(f"duplicate section code {sec}")
    SECTIONS.append(sec)
    if not rows:
        raise NumbersError(f"section {sec}: no rows in {path}")
    header = set(rows[0].keys())
    for c in cols:
        needed = (c,) if isinstance(c, str) else getattr(c[1], "needs", ())
        missing = [k for k in needed if k not in header]
        if missing:
            raise NumbersError(f"section {sec}: unresolved column(s) {missing} in {path}")
    if label_col and label_col not in header:
        raise NumbersError(f"section {sec}: unresolved label column {label_col} in {path}")
    rows = [r for r in rows if (where is None or where(r))]
    rel = Path(path).relative_to(PKG)
    out.append(f"\n## {sec}. {title}\n\nSource `{rel}` · SHA `{sha}`" + (f"\n\n{note}" if note else "") + "\n")
    hdr = ["id"] + [c if isinstance(c, str) else c[0] for c in cols] + ["label"]
    out.append("| " + " | ".join(hdr) + " |")
    out.append("|" + "---|" * len(hdr))
    for i, r in enumerate(rows, 1):
        vals = []
        for c in cols:
            if isinstance(c, str):
                vals.append(fmt(r.get(c)))
            else:
                vals.append(c[1](r))
        lab = r.get(label_col, "") if label_col else ""
        out.append(f"| {sec}-{i} | " + " | ".join(vals) + f" | {lab} |")


def main():
    out = ["# NUMBERS", "",
           "Every number the paper may use. Labels: **bound** (exact inequality evaluated on data), **reference** "
           "(attainable forecaster using the true dynamics), **learned** (trained model), **estimate** (Monte Carlo "
           "population quantity with interval). Horizons are restricted means E[min(λT, 27)] in Lyapunov times; "
           "primary score = future frames, ε = 0.3. Readings are the frozen margins only (FREEZE.md 2.8).",
           "", f"Freeze commit: `f750ca1`. Generated by `scripts/make_numbers.py` at SHA `{config.git_sha()}`."]

    rows, sha = read_csv(R / "system_table.csv")
    table(out, "S", "System table", R / "system_table.csv",
          ["system", "quantity", "dt", "value", ("95% CI", ci("ci95_lo", "ci95_hi"))], rows, sha)

    rows, sha = read_csv(R / "headline" / "headline.csv")
    cols = ["bits", "delta", "dt", "particles", "p0_eps0.3", "bound_eps0.3_future_mean", "bound_eps0.3_future_ci95",
            "bound_eps0.3_future_nocross", "PF_eps0.3_future_mean", "PF_eps0.3_future_ci95", "DI_eps0.3_future_mean",
            "DI_eps0.3_future_ci95", "persistence_eps0.3_future_mean", "climatology_eps0.3_future_mean",
            "pf_fallback_rate", "history_ref_label"]
    extra = [c for c in rows[0].keys() if "outlast" in c and "eps0.3_future" in c][:3]
    if not extra:
        raise NumbersError("headline: no outlast columns found")
    table(out, "H", "Headline, lorenz28, primary score (bound: 1,000 states; history reference: 300)",
          R / "headline" / "headline.csv", cols + extra, rows, sha, label_col=None,
          note="Columns bound_* are **bound**; PF_* (history reference), DI_*, persistence_*, climatology_* are "
               "**reference** (history_ref_label marks settings over the 5% fallback limit as unreliable); "
               "p0 and outlast fractions are **estimate**.")
    cols2 = ["bits", "delta", "dt", "particles"] + [c for c in (rows[0].keys() if rows else [])
                                                  if c.endswith("from_t0_mean") and "eps0.3" in c]
    table(out, "H0", "Headline, secondary score (from t = 0)", R / "headline" / "headline.csv", cols2, rows, sha,
          label_col=None)

    # H2: subset systems at Delta = 0.05 (added 2026-09-25, WO extension E0.2), bits 6 and 10, every particle count run
    h2 = []
    sha2 = ""
    for sysn in ("lorenz45", "l96_5"):
        rr, sha2 = read_csv(R / "headline_subsets" / sysn / "headline.csv")
        h2 += [r for r in rr if r["bits"] in ("6", "10") and r["dt"] == "0.01"]
    if h2:
        table(out, "H2", "Subset systems at Delta = 0.05: bound and references (lorenz45, l96_5; 6 and 10 bits)",
              R / "headline_subsets" / "lorenz45" / "headline.csv",
              ["system", "bits", "delta", "particles", "p0_eps0.3", "bound_eps0.3_future_mean", "bound_eps0.3_future_ci95",
               "bound_eps0.3_future_nocross", "PF_eps0.3_future_mean", "PF_eps0.3_future_ci95", "pf_fallback_rate",
               "history_ref_label", "DI_eps0.3_future_mean", "DI_eps0.3_future_ci95", "persistence_eps0.3_future_mean"],
              h2, sha2, label_col=None,
              note="Rows from results/headline_subsets/{lorenz45,l96_5}/headline.csv. bound_* = **bound**; PF_* (history "
                   "reference), DI_*, persistence_* = **reference**; history_ref_label marks rows above the 5% fallback "
                   "limit as unreliable (the 10-bit rows at both 1,500 and 3,000 particles); p0 = **estimate**.")

    p = R / "exchange_law" / "predicted_vs_measured.csv"
    rows, sha = read_csv(p)
    table(out, "X", "Exchange law: predicted vs measured (Δ = 0.02, 1,000 states)", p,
          ["system", "rate_bits", "role", "delta_hat_over_sigma_A", "pred", ("pred 95%", ci("pred_ci95_lo", "pred_ci95_hi")),
           "meas", ("meas 95%", ci("meas_ci95_lo", "meas_ci95_hi")), "err", "tol", "outcome", "second_author_pred",
           "second_author_err"], rows, sha, label_col="pred_label",
          note="pred = **estimate**; meas = **reference** (decode-and-integrate). The paper may say the law predicts "
               "held-out rates only for a system where all four held-out rates meet the criterion; none does.")
    p = R / "exchange_law" / "h_and_r_by_orientation.csv"
    rows, sha = read_csv(p)
    table(out, "R", "r by error orientation", p,
          ["system", "orientation", "delta_over_sigma_A", "H_mean", "frac_no_cross", "r_central",
           ("r 95%", ci("r_central_ci95_lo", "r_central_ci95_hi")), "r_ls_whole_range"], rows, sha)
    p = R / "exchange_law" / "fsle.csv"
    rows, sha = read_csv(p)
    table(out, "F", "Classical FSLE / λ", p, ["system", "scale_rel", "fsle_over_lambda", ("95%", ci("ci95_lo", "ci95_hi")),
                                            "frac_reached"], rows, sha)
    for name, title, cols in (
            ("distortion_kmeans", "k-means distortion", ["system", "rate_bits", "delta_over_sigma_A"]),
            ("di_vs_kmeans_rate", "Decode-and-integrate vs k-means rate (Δ = 0.02)",
             ["system", "rate_bits", "H_mean", ("95%", ci("H_ci95_lo", "H_ci95_hi")), "frac_no_cross"]),
            ("rvq_oracle", "Residual-VQ oracle horizons (Δ = 0.02)",
             ["system", "bits", "delta_calib_over_sigma_A", "H_mean", ("95%", ci("H_ci95_lo", "H_ci95_hi"))]),
            ("scalar_quantization", "Scalar quantization distortion",
             ["system", "levels", "rate_nominal_bits", "cells_used", "delta_calib_over_sigma_A",
              "delta_heldout_over_sigma_A", "heldout_unseen_frac"])):
        p = R / "dimension" / f"{name}.csv"
        rows, sha = read_csv(p)
        # section codes are fixed: DDI distortion, DDH decode-and-integrate vs rate (was a duplicate DDI before
        # 2026-09-25, WO extension E0.1), DRV residual VQ, DSC scalar quantization
        code = {"distortion_kmeans": "DDI", "di_vs_kmeans_rate": "DDH", "rvq_oracle": "DRV",
                "scalar_quantization": "DSC"}[name]
        table(out, code, title, p, cols, rows, sha)

    p = R / "history" / "history.csv"
    rows, sha = read_csv(p)
    table(out, "Y", "History reference: context sweep and sensitivity (dt = 0.005, 300 states)", p,
          ["method", "variant", "bits", "delta", "tau", "particles", "eps0.3_future_mean",
           ("95%", ci("eps0.3_future_lo95", "eps0.3_future_hi95")), "err0_rms_rel", "err0_median_rel", "fallback_rate"],
          rows, sha, where=lambda r: r.get("canonical", "True") == "True")

    p = R / "postfreeze" / "codebook_seeds_spread.csv"
    if p.exists():
        rows, sha = read_csv(p)
        table(out, "P", "POST-FREEZE robustness: k-means random_state 0-4 at 4 and 6 bits (frozen-seed codebook primary)", p,
              ["bits", "quantity", "frozen", "refit_min", "refit_max", "refit_mean", "refit_sd"], rows, sha,
              note="Post-freeze check, not pre-registered. At 4 bits random_state 4 is the frozen seed, so the refit set "
                   "contains the frozen codebook. decomp_* columns are **estimate**, bound_* are **bound** for their own "
                   "codebook. Per-codebook rows: results/postfreeze/codebook_seeds_rows.csv.")

    for fname, sec, title, cols, note in (
            ("exchange_law_variants.csv", "P2", "POST-FREEZE: exchange-law predictions by per-state h and by geometric-mean "
             "distortion, next to the frozen RMS prediction (criterion outcomes stay as frozen)",
             ["system", "rate_bits", "role", "meas", "frozen_pred_rms", "frozen_err", "frozen_outcome", "pred_per_state",
              ("95%", ci("pred_per_state_lo", "pred_per_state_hi")), "err_per_state", "clamped_share_per_state",
              "per_state_flag", "pred_geomean", ("95%", ci("pred_geomean_lo", "pred_geomean_hi")), "err_geomean",
              "clamped_share_geomean_states", "geomean_flag", "frozen_tolerance_info_only"],
             "Post-freeze, not pre-registered. meas = **reference**; predictions = **estimate**. The frozen criterion "
             "outcomes are unchanged; the tolerance column is informational. Per-state errors outside the calibrated "
             "h range are clamped to its end (clamped share shown next to every prediction), which biases those "
             "predictions upward; cells with more than 25% clamped are marked UNINFORMATIVE."),
            ("data_axis_B_cells.csv", "P3", "POST-FREEZE: B and C (sigma = 0) on the 20,000 tu data axis next to A (Delta 0.05)",
             ["bits", "cell", "n_seeds", "H", ("95%", ci("ci95_lo", "ci95_hi"))],
             "Post-freeze, not pre-registered. Cells are **learned**."),
            ("data_axis_B_comparisons.csv", "P4", "POST-FREEZE: data-axis paired differences",
             ["bits", "a", "b", "diff_a_minus_b", ("90%", ci("ci90_lo", "ci90_hi")), ("95%", ci("ci95_lo", "ci95_hi")),
              "reading", "a_near_b"], "Post-freeze **estimate**; readings use the frozen margins, for information. \"near\" applies the frozen near margin with C (sigma = 0) as the reference."),
            ("di_slope.csv", "P5", "POST-FREEZE: least-squares decode-and-integrate slope (Lyapunov times per bit)",
             ["system", "fit", "rates", "slope_lyap_per_bit", ("95%", ci("ci95_lo", "ci95_hi")), "H_by_rate"],
             "Post-freeze **estimate**. Decode-and-integrate on the 1,000-state confirmation panel, Delta 0.02, future "
             "frames, eps 0.3; interval by bootstrap over panel states, paired across rates."),
            ("slope_x_deff.csv", "P6", "POST-FREEZE: slope x D_eff and implied r = ln2/(slope x D_eff), beside local r "
             "at codebook scales (section R)",
             ["system", "fit", "slope_lyap_per_bit", "d_eff", "slope_x_deff", ("95%", ci("slope_x_deff_lo", "slope_x_deff_hi")),
              "implied_r", ("95%", ci("implied_r_lo", "implied_r_hi")), "local_r_codebook_scales_median",
              "local_r_codebook_scales_min", "local_r_codebook_scales_max", "local_r_scale_range",
              "local_r_ls_whole_range", "rates_below_tolerance", "implied_r_R8_minus_R6",
              ("95%", ci("settle_ci95_lo", "settle_ci95_hi")), "note"],
             "Post-freeze **estimate**. Intervals propagate the slope bootstrap (panel states) and the D_eff bootstrap "
             "(calibration trajectories) jointly. Fits: all rates 4-12; the frozen even rates {6,8,10,12}; all rates 6-12; "
             "all rates 8-12. The R8-12 rows carry the paired difference of implied r against the R6-12 fit (settling "
             "check; shared bootstrap replicates). Local r: fresh orientation, central differences at h-grid points "
             "between the 12-bit and 4-bit calibration distortions. l96_10 reaches below the 0.3 sigma_A tolerance only "
             "at 12 bits and l96_20 never within 4-12 bits, so their slopes and implied r are not meaningful as "
             "exchange rates.")):
        p = R / "postfreeze" / fname
        if p.exists():
            rows, sha = read_csv(p)
            table(out, sec, title, p, cols, rows, sha, note=note)

    lj = R / "learned" / "learned.json"
    if lj.exists():
        rows, sha = read_csv(R / "learned" / "cells.csv")
        table(out, "L", "Learned cells (seeds pooled; 1,000 states; H300 = history panel)", R / "learned" / "cells.csv",
              ["system", "arm", "bits", "delta", "noise", "n_traj", "n_seeds", "H_eps0.3_future",
               ("95%", ci("H_eps0.3_future_lo", "H_eps0.3_future_hi")), "H300_eps0.3_future", "H_eps0.3_from_t0",
               "Hdiag_primary", "repeat_fraction_mean", "true_repeat_fraction", "stalled_seeds", "recon_rmse_rel",
               "current_token_rmse_rel", "probe_linear_recon_rmse_rel", "probe_linear_H", "probe_mlp_recon_rmse_rel",
               "probe_mlp_H", "temperature_mean", "params_total", "params_backbone", "params_head", "train_flops"],
              rows, sha)
        rows, sha = read_csv(R / "learned" / "comparisons.csv")
        table(out, "C", "Paired comparisons and frozen readings", R / "learned" / "comparisons.csv",
              ["comparison", "system", "bits", "delta", "score", "n_states", "diff_a_minus_b",
               ("90%", ci("ci90_lo", "ci90_hi")), ("95%", ci("ci95_lo", "ci95_hi")), "reading"], rows, sha)
        rows, sha = read_csv(R / "learned" / "extra.csv")
        table(out, "E", "Outlast fractions, A as a fraction of the bound, near-reference tests, probe reconstruction",
              R / "learned" / "extra.csv",
              ["kind", "arm", "system", "bits", "delta", "score", "outlast", "ties", "ratio",
               ("95%", ci("ci95_lo", "ci95_hi")), "ref_minus_model", "upper95", "near", "current_token_rmse_rel",
               "probe_rmse_rel_per_seed", "probe_below_baseline_all_seeds"], rows, sha)
    p = R / "decomposition" / "decomposition.csv"
    if p.exists():
        rows, sha = read_csv(p)
        table(out, "M", "Single-frame decomposition, lorenz28 (Amendment 1; 150,000 calibration states)", p,
              ["bits", "eps", "O0_over_I0", "passes_original_1e-10", "passes_amended_1e-6",
               "T_info", ("95%", ci("T_info_lo", "T_info_hi")), "T_codebook", ("95%", ci("T_codebook_lo", "T_codebook_hi")),
               "T_codebook_bc", "T_projected_DI", ("95%", ci("T_projected_DI_lo", "T_projected_DI_hi")),
               "O_share_at_Tinfo", ("95%", ci("O_share_at_Tinfo_lo", "O_share_at_Tinfo_hi")), "Obc_share_at_Tinfo",
               ("95%", ci("Obc_share_at_Tinfo_lo", "Obc_share_at_Tinfo_hi")), "E_share_at_Tinfo",
               ("95%", ci("E_share_at_Tinfo_lo", "E_share_at_Tinfo_hi")), "min_cell", "median_cell"], rows, sha,
              note="T_info is a **bound** (single-frame information bound on ensemble RMSE); T_codebook, T_projected_DI "
                   "and the shares are **estimate**. Known-zero test: original threshold 1e-10 fails at 4 bits; "
                   "amended threshold 1e-6 (FREEZE.md Amendment 1) passes at every rate.")
    import re as _re
    ids = [m.group(1) for l in out for m in [_re.match(r"^\| ([A-Z0-9]+-\d+) \|", l)] if m]
    dup = sorted({i for i in ids if ids.count(i) > 1})
    if dup:
        raise NumbersError(f"duplicate IDs: {dup[:10]} ({len(dup)} total)")
    (PKG / "NUMBERS.md").write_text("\n".join(out) + "\n")
    print("wrote NUMBERS.md", sum(1 for l in out if l.startswith("| ") and not l.startswith("| id")), "rows")


if __name__ == "__main__":
    main()
