"""Build NUMBERS.md: every number the paper may use, with its label, source file and producing SHA.

The paper takes numbers only from this table. Each row has a stable id (section-row). Values are copied
from result files, never retyped. Intervals are 95% unless the column says otherwise.
"""
import csv
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from th import config  # noqa: E402

R = config.RESULTS
PKG = config.PKG


def read_csv(p):
    sha = ""
    lines = []
    with open(p) as fh:
        for l in fh:
            if l.startswith("#"):
                if "git_sha=" in l:
                    sha = l.split("git_sha=")[1].split(";")[0].split()[0]
                continue
            lines.append(l)
    rows = list(csv.DictReader(lines))
    for k in ("git_sha", "sha"):
        if not sha and rows and rows[0].get(k):
            sha = rows[0][k]
    return rows, sha


def fmt(v):
    if v is None or v == "":
        return ""
    try:
        f = float(v)
    except (TypeError, ValueError):
        return str(v)
    if f != f:
        return "nan"
    if f == int(f) and abs(f) < 1e6 and "." not in str(v):
        return str(int(f))
    a = abs(f)
    if a != 0 and (a < 1e-3 or a >= 1e5):
        return f"{f:.3e}"
    return f"{f:.4f}"


def table(out, sec, title, path, cols, rows, sha, where=None, label_col="label", note=""):
    rows = [r for r in rows if (where is None or where(r))]
    rel = Path(path).relative_to(PKG)
    out.append(f"\n## {sec}. {title}\n\nSource `{rel}` · SHA `{sha}`" + (f"\n\n{note}" if note else "") + "\n")
    hdr = ["id"] + [c if isinstance(c, str) else c[0] for c in cols] + ["label"]
    out.append("| " + " | ".join(hdr) + " |")
    out.append("|" + "---|" * len(hdr))
    for i, r in enumerate(rows, 1):
        vals = []
        for c in cols:
            if isinstance(c, str):
                vals.append(fmt(r.get(c)))
            else:
                vals.append(c[1](r))
        lab = r.get(label_col, "") if label_col else ""
        out.append(f"| {sec}-{i} | " + " | ".join(vals) + f" | {lab} |")


def ci(lo, hi):
    return lambda r: f"[{fmt(r.get(lo))}, {fmt(r.get(hi))}]" if r.get(lo) not in (None, "") else ""


def main():
    out = ["# NUMBERS", "",
           "Every number the paper may use. Labels: **bound** (exact inequality evaluated on data), **reference** "
           "(attainable forecaster using the true dynamics), **learned** (trained model), **estimate** (Monte Carlo "
           "population quantity with interval). Horizons are restricted means E[min(λT, 27)] in Lyapunov times; "
           "primary score = future frames, ε = 0.3. Readings are the frozen margins only (FREEZE.md 2.8).",
           "", f"Freeze commit: `f750ca1`. Generated by `scripts/make_numbers.py` at SHA `{config.git_sha()}`."]

    rows, sha = read_csv(R / "system_table.csv")
    table(out, "S", "System table", R / "system_table.csv",
          ["system", "quantity", "dt", "value", ("95% CI", ci("ci95_lo", "ci95_hi"))], rows, sha)

    rows, sha = read_csv(R / "headline" / "headline.csv")
    cols = ["bits", "delta", "dt", "particles", "p0_eps0.3", "bound_eps0.3_future_mean", "bound_eps0.3_future_ci95",
            "bound_eps0.3_future_nocross", "PF_eps0.3_future_mean", "PF_eps0.3_future_ci95", "DI_eps0.3_future_mean",
            "DI_eps0.3_future_ci95", "persistence_eps0.3_future_mean", "climatology_eps0.3_future_mean",
            "pf_fallback_rate", "history_ref_label"]
    cols = [c for c in cols if rows and c in rows[0]]
    extra = [c for c in (rows[0].keys() if rows else []) if "outlast" in c and "eps0.3_future" in c][:3]
    table(out, "H", "Headline, lorenz28, primary score (bound: 1,000 states; history reference: 300)",
          R / "headline" / "headline.csv", cols + extra, rows, sha, label_col=None,
          note="Columns bound_* are **bound**; PF_* (history reference), DI_*, persistence_*, climatology_* are "
               "**reference** (history_ref_label marks settings over the 5% fallback limit as unreliable); "
               "p0 and outlast fractions are **estimate**.")
    cols2 = ["bits", "delta", "dt", "particles"] + [c for c in (rows[0].keys() if rows else [])
                                                  if c.endswith("from_t0_mean") and "eps0.3" in c]
    table(out, "H0", "Headline, secondary score (from t = 0)", R / "headline" / "headline.csv", cols2, rows, sha,
          label_col=None)

    p = R / "exchange_law" / "predicted_vs_measured.csv"
    rows, sha = read_csv(p)
    table(out, "X", "Exchange law: predicted vs measured (Δ = 0.02, 1,000 states)", p,
          ["system", "rate_bits", "role", "delta_hat_over_sigma_A", "pred", ("pred 95%", ci("pred_ci95_lo", "pred_ci95_hi")),
           "meas", ("meas 95%", ci("meas_ci95_lo", "meas_ci95_hi")), "err", "tol", "outcome", "second_author_pred",
           "second_author_err"], rows, sha, label_col="pred_label",
          note="pred = **estimate**; meas = **reference** (decode-and-integrate). The paper may say the law predicts "
               "held-out rates only for a system where all four held-out rates meet the criterion; none does.")
    p = R / "exchange_law" / "h_and_r_by_orientation.csv"
    rows, sha = read_csv(p)
    table(out, "R", "r by error orientation", p,
          ["system", "orientation", "delta_over_sigma_A", "H_mean", "frac_no_cross", "r_central",
           ("r 95%", ci("r_central_ci95_lo", "r_central_ci95_hi")), "r_ls_whole_range"], rows, sha)
    p = R / "exchange_law" / "fsle.csv"
    rows, sha = read_csv(p)
    table(out, "F", "Classical FSLE / λ", p, ["system", "scale_rel", "fsle_over_lambda", ("95%", ci("ci95_lo", "ci95_hi")),
                                            "frac_reached"], rows, sha)
    for name, title, cols in (
            ("distortion_kmeans", "k-means distortion", ["system", "rate_bits", "delta_over_sigma_A"]),
            ("di_vs_kmeans_rate", "Decode-and-integrate vs k-means rate (Δ = 0.02)",
             ["system", "rate_bits", "H_mean", ("95%", ci("H_ci95_lo", "H_ci95_hi")), "frac_no_cross"]),
            ("rvq_oracle", "Residual-VQ oracle horizons (Δ = 0.02)",
             ["system", "bits", "delta_calib_over_sigma_A", "H_mean", ("95%", ci("H_ci95_lo", "H_ci95_hi"))]),
            ("scalar_quantization", "Scalar quantization distortion",
             ["system", "levels", "rate_nominal_bits", "cells_used", "delta_calib_over_sigma_A",
              "delta_heldout_over_sigma_A", "heldout_unseen_frac"])):
        p = R / "dimension" / f"{name}.csv"
        rows, sha = read_csv(p)
        table(out, f"D{name[:2].upper()}", title, p, cols, rows, sha)

    p = R / "history" / "history.csv"
    rows, sha = read_csv(p)
    table(out, "Y", "History reference: context sweep and sensitivity (dt = 0.005, 300 states)", p,
          ["method", "variant", "bits", "delta", "tau", "particles", "eps0.3_future_mean",
           ("95%", ci("eps0.3_future_lo95", "eps0.3_future_hi95")), "err0_rms_rel", "err0_median_rel", "fallback_rate"],
          rows, sha, where=lambda r: r.get("canonical", "True") == "True")

    lj = R / "learned" / "learned.json"
    if lj.exists():
        rows, sha = read_csv(R / "learned" / "cells.csv")
        table(out, "L", "Learned cells (seeds pooled; 1,000 states; H300 = history panel)", R / "learned" / "cells.csv",
              ["system", "arm", "bits", "delta", "noise", "n_traj", "n_seeds", "H_eps0.3_future",
               ("95%", ci("H_eps0.3_future_lo", "H_eps0.3_future_hi")), "H300_eps0.3_future", "H_eps0.3_from_t0",
               "Hdiag_primary", "repeat_fraction_mean", "true_repeat_fraction", "stalled_seeds", "recon_rmse_rel",
               "current_token_rmse_rel", "probe_linear_recon_rmse_rel", "probe_linear_H", "probe_mlp_recon_rmse_rel",
               "probe_mlp_H", "temperature_mean", "params_total", "params_backbone", "params_head", "train_flops"],
              rows, sha)
        rows, sha = read_csv(R / "learned" / "comparisons.csv")
        table(out, "C", "Paired comparisons and frozen readings", R / "learned" / "comparisons.csv",
              ["comparison", "system", "bits", "delta", "score", "n_states", "diff_a_minus_b",
               ("90%", ci("ci90_lo", "ci90_hi")), ("95%", ci("ci95_lo", "ci95_hi")), "reading"], rows, sha)
        rows, sha = read_csv(R / "learned" / "extra.csv")
        table(out, "E", "Outlast fractions, A as a fraction of the bound, near-reference tests, probe reconstruction",
              R / "learned" / "extra.csv",
              ["kind", "arm", "system", "bits", "delta", "score", "outlast", "ties", "ratio",
               ("95%", ci("ci95_lo", "ci95_hi")), "ref_minus_model", "upper95", "near", "current_token_rmse_rel",
               "probe_rmse_rel_per_seed", "probe_below_baseline_all_seeds"], rows, sha)
    p = R / "decomposition" / "decomposition.csv"
    if p.exists():
        rows, sha = read_csv(p)
        table(out, "M", "Single-frame decomposition, lorenz28 (Amendment 1; 150,000 calibration states)", p,
              ["bits", "eps", "O0_over_I0", "passes_original_1e-10", "passes_amended_1e-6",
               "T_info", ("95%", ci("T_info_lo", "T_info_hi")), "T_codebook", ("95%", ci("T_codebook_lo", "T_codebook_hi")),
               "T_codebook_bc", "T_projected_DI", ("95%", ci("T_projected_DI_lo", "T_projected_DI_hi")),
               "O_share_at_Tinfo", ("95%", ci("O_share_at_Tinfo_lo", "O_share_at_Tinfo_hi")), "Obc_share_at_Tinfo",
               ("95%", ci("Obc_share_at_Tinfo_lo", "Obc_share_at_Tinfo_hi")), "E_share_at_Tinfo",
               ("95%", ci("E_share_at_Tinfo_lo", "E_share_at_Tinfo_hi")), "min_cell", "median_cell"], rows, sha,
              note="T_info is a **bound** (single-frame information bound on ensemble RMSE); T_codebook, T_projected_DI "
                   "and the shares are **estimate**. Known-zero test: original threshold 1e-10 fails at 4 bits; "
                   "amended threshold 1e-6 (FREEZE.md Amendment 1) passes at every rate.")
    (PKG / "NUMBERS.md").write_text("\n".join(out) + "\n")
    print("wrote NUMBERS.md", sum(1 for l in out if l.startswith("| ") and not l.startswith("| id")), "rows")


if __name__ == "__main__":
    main()
