"""Render audit and numerical reports from their saved receipts."""
import os
os.environ['JAX_PLATFORMS']='cpu'
os.environ['JAX_ENABLE_X64']='true'
import json
from pathlib import Path
ROOT=Path(__file__).resolve().parent
def stats():
    d=json.loads((ROOT/'runs/audit/acd_stats_audit.json').read_text())
    lines=['# ACD statistical audit — v2.3','', '**PASS.**' if d['all_prescribed_checks_pass'] else '**R-stat required.**',f"Synthetic only; host {d['host']}; seed {d['seed']}; {d['null_panels']} panels/configuration; {d['power_panels']} panels/power cell; {d['wall_seconds']:.2f} CPU wall seconds.",'','Predictable m-independent bets capped at .9, prefix log-capitals, monotone integer bisection and outward rounding. Per-side alpha/2 is used for two-sided bounds. The audit imports no experiment or truth module.','',f"Monotonicity: {d['monotonicity']['sequences']} sequences on a 1e-4 grid, {d['monotonicity']['violations']} violations. Exact CP error {d['exact']['cp_max_absolute_error']:.3g}; McNemar error {d['exact']['mcnemar_max_absolute_error']:.3g}.",'','| Sequence | Candidate | 99% interval | Rejected | Peak capital |','|---|---|---|---|---|']
    for w in d['witnesses']:lines.append(f"| 200 × {w['value']} | {w['candidate']} | {w['interval']} | {w['candidate_rejected']} | {w['peak']:.6f} |")
    lines+=['','Both previous unrejected real-mean counterexamples are now rejected by their own capital; continuous coverage no longer relies on scanning a non-monotone sublevel set.','', 'Null criterion: nominal + 2·sqrt(nominal·(1−nominal)/N). Half empty is P(0)=.5, otherwise uniform 1–8; eight-only errors fail an entire eight-answer case.','', '| Sizes | Error mechanism | False PASS | Limit |','|---|---|---|---|']
    for r in d['null_R0']:lines.append(f"| {r['sizes']} | {r['mechanism']} | {r['rate']:.5f} | {r['limit']:.5f} |")
    lines+=['','| R2 null shape | Noncoverage | Limit |','|---|---|---|']
    for r in d['null_R2']:lines.append(f"| {r['shape'] if 'shape' in r else r['theme']} | {r['rate']:.5f} | {r['limit']:.5f} |")
    c=d['counterexample'];lines+=['','The executor’s original population has answer-level accuracy **0.888**, case-level accuracy **0.953333**. It is an alternative under the explicitly changed estimand. The old no-error bootstrap PASS frequency is '+f"{c['old_no_error_PASS']['rate']:.5f}; the new procedure gives {c['new_PASS']['rate']:.5f}. The answer-level point floor remains .90. Thirty perfect nonempty cases with 100 answers give L=.883 and INSUFFICIENT.",'','Power (descriptive synthetic probabilities):','', '| Case accuracy | Nonempty cases | Mechanism | PASS probability | MC SE |','|---|---|---|---|---|']
    for r in d['power_R0']:lines.append(f"| {r['accuracy']} | {r['nonempty']} | {r['mechanism']} | {r['rate']:.4f} | {r['mc_se']:.4f} |")
    lines+=['','| R2a Δ | Shape | Route power | MC SE | Strong power |','|---|---|---|---|---|']
    for r in d['power_R2']:lines.append(f"| {r['delta']} | {r['theme']} | {r['publish']['rate']:.4f} | {r['publish']['mc_se']:.4f} | {r['strong']['rate']:.4f} |")
    lines+=['','R2 power assumes its calibration prerequisites. No R-stat fallback fired. Exact values, Monte Carlo counts, power estimates and source hashes: `ACD_STATS_AUDIT_v2.3.json`.','']
    for name,sha in d['code_hashes'].items():lines.append(f'- {name}: `{sha}`')
    (ROOT/'ACD_STATS_AUDIT.md').write_text('\n'.join(lines)+'\n');(ROOT/'ACD_STATS_AUDIT_v2.3.json').write_text(json.dumps(d,indent=2)+'\n')
def numerical():
    d=json.loads((ROOT/'runs/audit/acd_numerical.json').read_text());null=json.loads((ROOT/'runs/null/null.json').read_text());cfg=d['settings'];g=d['implementation']
    lines=['# ACD numerical report — v2.3','', 'Stage 0 completed on sulaco CPU, float64. Only hard stops H1–H3 govern continuation.','', '| Check | Result |','|---|---|',f"| Joint adjoint, all 41 components, centered eps=1e-6 | max absolute error {d['joint_adjoint_error']:.12g} <1e-6 |",f"| JAX RK4 over 11 frames | relative discrepancy {d['jax_relative_match']:.12g} <1e-12 |",f"| Gaussian sampler | PASS={g['passed']}; mean {g['max_mean_mcse']:.3f} MC SE, variance {g['max_variance_mcse']:.3f} MC SE; extreme-direction variance ratios {g['extreme_variance_ratios']} |",f"| dt versus dt/2 | PASS={d['dtcheck']['passed']}; ≤3 LT max draw-answer change {max(d['dtcheck']['answer_change'][:6]):.7f}; max classification change {max(d['dtcheck']['classification_change'][:6]):.7f} |",f"| Climatology | 4096 independently seeded F=8 states; Jbar={null['jbar']:.9f}; {null['seconds']:.2f}s |",'', '| Benchmark, including compilation/forecast/diagnostics | Seconds |','|---|---|',f"| Ordinary case | {d['ordinary_seconds']:.3f} |",f"| Four-site Q refit | {d['four_site']['seconds']:.3f} |",f"| All-site A refit | {d['all_site']['seconds']:.3f} |",'', f"Initial serial 8-core projection: 1.2 × (400 ordinary +1200 four-site +300 all-site) = **{d['projection_seconds']/3600:.3f} hours**. This includes a 20% rerun allowance and counts first-compilation cost conservatively for every run. Benchmarks used development case199/dtcheck case0; no confirmation input.",'', '**R-time fired.** Apply cuts in order: '+', '.join(cfg['cuts'])+f". R5 population cap={cfg['r5_population']}; warmup={cfg['warmup']}; draws={cfg['draws']} per chain. The serial projection after the population cut is 15.570h, before the final draw reduction. The final settings continue as §14 directs, even if a serial projection remains over budget. Stage1 runs independent cases in parallel on reserved CPU affinities; no GPU use.",'', 'dt remains .01. No R-grad, R-impl or R-dt fallback fired. The Stage0 benchmark development case is resampled at the production draw count before Stage1 scoring.','', 'IDs and sub roles are fixed in acd_protocol.py. The complete planned leaf uniqueness assertion covers '+str(d['seeds']['count'])+' leaves; no overlap with inherited IDs. Full records: `receipts/acd_numerical.json`, `runs/null/null.npz`, `runs/acd_access.jsonl`, and `runs/resolutions.jsonl`.','', '```json',json.dumps(d['seeds'],indent=2),'```']
    (ROOT/'ACD_NUMERICAL_REPORT.md').write_text('\n'.join(lines)+'\n')
if __name__=='__main__':stats();numerical()
