"""Generate the paper-facts note (R_Adapt-The-Physics-Paper-Facts-2026-09) from the repository: source lines are quoted
verbatim with file:line, numbers are read from committed config/result files and instantiated models. Nothing is typed
from memory. Writes stage2/results/paper_facts.md.

Also: `numbers` mode writes stage2/results/numbers_export.md = the APV* and APS* sections of adapt_physics/NUMBERS.md
with the checker status (a fresh build under the strict checker, plus a negative test that must raise).
Usage: python stage2/scripts/s2_paper_facts.py facts | numbers
"""
import inspect
import json
import platform
import re
import subprocess
import sys
from pathlib import Path

import numpy as np
import torch
import yaml

HERE = Path(__file__).resolve()
PKG = HERE.parents[2]
REPO = PKG.parent
sys.path.insert(0, str(PKG))
sys.path.insert(0, str(PKG / "pivot"))
sys.path.insert(0, str(PKG / "scripts"))
sys.path.insert(0, str(PKG / "stage2" / "scripts"))
sys.path.insert(0, str(REPO / "tokens_horizon"))
from ap import config  # noqa: E402

OUT = PKG / "stage2" / "results"


def sh(*a):
    return subprocess.run(a, cwd=REPO, capture_output=True, text=True).stdout.strip()


def quote(path, pattern, before=0, after=0, all_=False):
    """Verbatim source lines matching a regex (with context), as a fenced block with file:line."""
    p = REPO / path
    lines = p.read_text().splitlines()
    hits = [i for i, l in enumerate(lines) if re.search(pattern, l)]
    if not hits:
        raise ValueError(f"pattern {pattern!r} not found in {path}")
    blocks = []
    for i in (hits if all_ else hits[:1]):
        a, b = max(0, i - before), min(len(lines), i + after + 1)
        blocks.append(f"`{path}:{a + 1}-{b}`\n```python\n" + "\n".join(lines[a:b]) + "\n```")
    return "\n".join(blocks)


def src_of(obj, rel):
    lines, start = inspect.getsourcelines(obj)
    return f"`{rel}:{start}-{start + len(lines) - 1}`\n```python\n" + "".join(lines).rstrip() + "\n```"


def doc_end(path):
    lines = (REPO / path).read_text().splitlines()
    return next(i + 1 for i, l in enumerate(lines) if i > 0 and l.strip().endswith('"""'))


def jl(p):
    return json.loads((PKG / p).read_text())


def facts():
    head = sh("git", "rev-parse", "--short", "HEAD")
    dirty = sh("git", "status", "--porcelain", "--", "adapt_physics")
    fz = yaml.safe_load((PKG / "ap_freeze.yaml").read_text())
    pv = yaml.safe_load((PKG / "pivot" / "pv_freeze.yaml").read_text())
    s2 = yaml.safe_load((PKG / "stage2" / "s2_freeze.yaml").read_text())
    bc = jl("pivot/results/beta_calibration.json")
    dc = jl("results/drag_calibration.json")
    L = ["# Adapt the Physics: paper facts", "",
         f"Generated by `adapt_physics/stage2/scripts/s2_paper_facts.py` from branch `paper/adapt-physics-2026-09` at `{head}`"
         + (" (with uncommitted result files)" if dirty else "") + ".",
         "- Code is quoted verbatim, with file and line numbers.",
         "- Numbers are read from committed configuration and result files, or from instantiated models.",
         "- Nothing is typed from memory.", ""]
    # 1 equations
    from ap.solver import KolmoDrag
    from th import kolmogorov as K
    m = KolmoDrag(np.array([40.0]), alpha=dc["alpha"], beta=bc["beta"])
    L += ["## 1. Truth and model equations", "",
          "Base equations and numerics (module docstring):", "",
          f"`tokens_horizon/th/kolmogorov.py:1-{doc_end('tokens_horizon/th/kolmogorov.py')}`\n```\n{K.__doc__.strip()}\n```", "",
          f"Constants: N = {K.N_GRID}, forcing wavenumber n = {K.N_FORCE}, dt = {K.DT}; the solver instance has "
          f"`mask` keeping |kx|, |ky| ≤ N//3 = {K.N_GRID // 3} with k = 0 removed, dtype {m.dtype}.", "",
          quote("tokens_horizon/th/kolmogorov.py", r"kmax = N // 3", 0, 1),
          quote("tokens_horizon/th/kolmogorov.py", r"forcing = \(-self\.n", 0, 1),
          quote("tokens_horizon/th/kolmogorov.py", r"def rhs\(self, wh\)", 0, 8),
          quote("tokens_horizon/th/kolmogorov.py", r"def step\(self, wh\)", 0, 7), "",
          "**Forcing amplitude:** the body force is sin(n y) in x with amplitude 1, so the vorticity forcing is "
          "−n cos(n y) (see the line above). The stage-2 two-parameter item multiplies it by A per trajectory:", "",
          quote("adapt_physics/ap/solver.py", r"def set_amp", 0, 4), "",
          "Drag and the per-trajectory Re enter the integrating factor; World C adds β:", "",
          quote("adapt_physics/ap/solver.py", r"def set_re", 0, 5),
          quote("adapt_physics/ap/solver.py", r"def rhs\(self, wh\)", 0, 5), "",
          "| World | Truth right-hand side (vorticity) | Physics family used by P1, H |", "|---|---|---|",
          f"| D | −u·∇ω + Re⁻¹∇²ω − α ω − n A cos(n y), α = {dc['alpha']:.7f} | −u·∇ω + Re⁻¹∇²ω − n cos(n y) (no drag) |",
          f"| C | World D − β_T v, β_T = {bc['beta']:.7f} (v = −∂ψ/∂x) | same no-drag family (no drag, no β) |", "",
          f"A = 1 except in stage-2 item 3. Drag calibration: {dc['definition']}, achieved share {dc['share']:.5f}. "
          f"β calibration: start {bc['start']}, target |η(β)/η(0) − 1| = {bc['target']}, achieved {bc['rel_change']:+.5f}.", ""]
    # 2 codex
    cm = (PKG / "pivot" / "CODEX_MISMATCH.md").read_text()
    L += ["## 2. Codex mismatch term", "", "`adapt_physics/pivot/CODEX_MISMATCH.md`, verbatim:", "", "````markdown", cm.rstrip(), "````", "",
          "Implemented β term (World C only; `beta` = β_T above):", "", quote("adapt_physics/ap/solver.py", r"r = r - self.beta", 2, 0), ""]
    # 3 hybrid
    import hybrid
    from hybrid import Correction
    g = Correction(1.0)
    hi = jl("runs/train/H_D/info.json")
    L += ["## 3. Hybrid H", "", f"`adapt_physics/pivot/hybrid.py` docstring:\n```\n{hybrid.__doc__.strip()}\n```", "",
          f"Correction parameters (instantiated): **{g.n_params():,}**. The correction is **continuous-time** (inside the right-hand side):", "",
          src_of(hybrid.HybridSolver, "adapt_physics/pivot/hybrid.py"), "",
          "Training (docstring and constants of `adapt_physics/pivot/scripts/pv_train_h.py`):", "",
          quote("adapt_physics/pivot/scripts/pv_train_h.py", r"^STEPS, BATCH", 0, 0),
          quote("adapt_physics/pivot/scripts/pv_train_h.py", r"p = m.to_phys\(m.flow", 0, 1),
          quote("adapt_physics/pivot/scripts/pv_train_h.py", r"opt = torch.optim.AdamW", 0, 1),
          quote("adapt_physics/pivot/scripts/pv_train_h.py", r"if v < best:", 0, 2), "",
          "| Model | Seed | Steps | Batch | Rollout frames | Best step | Pure-physics val loss | Best val loss | Train s |", "|---|---|---|---|---|---|---|---|---|"]
    for d in sorted((config.RUNS / "train").glob("H_*/info.json")):
        i = json.loads(d.read_text())
        L.append(f"| {d.parent.name} | {i.get('seed', 0)} | {i['steps']} | {i['batch']} | {i['rollout_frames']} | {i['best_step']} | "
                 f"{i['val_loss_pure_physics']:.3e} | {i['best_val']:.3e} | {i['train_seconds']:.0f} |")
    import ap.arms as A
    L += ["", "Identification misfit and golden-section search (the same code for P1, P1x and H):", "", src_of(A.identify, "adapt_physics/ap/arms.py"), "",
          "The H search range is [25, 80]; P1 and P1x use the default [25, 70]:", "",
          quote("adapt_physics/stage2/scripts/s2_eval.py", r"lo=25.0, hi=80.0", 0, 0), ""]
    # 4 FNO arms
    from ap.fno import ARMS, build
    import ap_train
    L += ["## 4. Learned opponents and diagnostics", "", "`adapt_physics/ap/fno.py` architecture (docstring):", "",
          f"```\n{sys.modules['ap.fno'].__doc__.strip()}\n```", "", "| Arm | Input frames | Width | Re channel | Data | Parameters (instantiated) |",
          "|---|---|---|---|---|---|"]
    for a, (n_in, w, rc, data) in ARMS.items():
        L.append(f"| {a} | {n_in} | {w} | {rc} | {data} | {build(a).n_params():,} |")
    L += ["", f"Training (`adapt_physics/scripts/ap_train.py`): steps {ap_train.STEPS}, batch {ap_train.BATCH}, unrolled "
          f"steps {ap_train.UNROLL}, validation every {ap_train.VAL_EVERY}.", "",
          quote("adapt_physics/scripts/ap_train.py", r"^Samples:", 0, 6),
          quote("adapt_physics/scripts/ap_train.py", r"noise = \(rng.standard_normal", 0, 0), "",
          "Data blocks (conditions = distinct Re values; states = trajectories × frames):", "", "| Set | World | Re | Trajectories | Frames | States | Seed |", "|---|---|---|---|---|---|---|"]
    for f, wd in (("results/data_blocks.json", "D"), ("pivot/results/data_blocks_C.json", "C"), ("stage2/results/data_blocks.json", "D/C")):
        for k, v in jl(f).items():
            if isinstance(v, dict) and "n_traj" in v:
                wk = k.rsplit("_", 1)[1] if wd == "D/C" else wd
                L.append(f"| {k} | {wk} | {v['re']} | {v['n_traj']} | {v['n_frames']} | {v['n_traj'] * v['n_frames']} | {v['seed']} |")
    L += ["", "| Model | Seed | Parameters | Steps | Best step | Train s |", "|---|---|---|---|---|---|"]
    for d in sorted((config.RUNS / "train").glob("*/info.json")):
        i = json.loads(d.read_text())
        if d.parent.name.startswith("H_"):
            continue
        L.append(f"| {d.parent.name} | {i.get('seed', 0)} | {i['params']:,} | {i['steps']} | {i['best_step']} | {i['train_seconds']:.0f} |")
    # 5 observation, scoring, bootstrap
    from th import score
    import s2_analysis
    L += ["", "## 5. Observation model, change time, scores, bootstrap", "",
          quote("adapt_physics/ap/solver.py", r"def obs_noise", 0, 2),
          quote("adapt_physics/stage2/scripts/s2_data.py", r"u = rng.uniform\(0, 1, n\)", 0, 0),
          quote("adapt_physics/stage2/scripts/s2_data.py", r"s = np.clip\(np.round\(u \* STEPS_PER_OBS\)", 0, 7), "",
          f"Observation interval Δ = {fz['observation']['interval']}; windows (stage 2) {s2['part_A']['windows']}; the forecast "
          f"starts from the noisy observation at the window's last frame. Horizon (restricted mean, W = 10 Lyapunov times of the test system):", "",
          src_of(score.horizon, "tokens_horizon/th/score.py"), "",
          "S(k) (share of states still within tolerance at k Lyapunov times; censored states survive):", "",
          quote("adapt_physics/stage2/scripts/s2_analysis.py", r"S1=float\(np.mean", 0, 0), "",
          "Bootstrap (stage 2, seed-pooled; trajectories resampled, then seeds within each trajectory):", "",
          src_of(s2_analysis.pooled_boot, "adapt_physics/stage2/scripts/s2_analysis.py"),
          quote("adapt_physics/stage2/scripts/s2_analysis.py", r"^REPS, DELTA", 0, 0),
          quote("adapt_physics/stage2/scripts/s2_analysis.py", r"def boot_idx", 0, 1), "",
          f"Single-seed intervals (stages 1 and pivot, part B): `th.score.bootstrap_mean` / `paired_diff` "
          f"(reps and seed from `tokens_horizon/freeze.yaml`).", ""]
    # 6 lambda sigma
    L += ["## 6. Lyapunov exponent and σ_A", "", "| World | System | λ [95%] | σ_A | Chaotic | Source |", "|---|---|---|---|---|---|"]
    srcs = [("D", "results/chaos_gate.json"), ("D", "pivot/results/chaos_gate_D.json"), ("C", "pivot/results/chaos_gate_C.json"),
            ("D (two-parameter)", "stage2/results/chaos_2p.json")]
    for wd, f in srcs:
        for k, v in sorted(((k, v) for k, v in jl(f).items() if isinstance(v, dict)), key=lambda kv: (kv[1]["Re"], kv[1].get("amp", 1))):
            nm = k if "amp" not in v else f"Re {v['Re']}, A = {v['amp']}"
            L.append(f"| {wd} | {nm} | {v['lam']:.5f} [{v['lam_ci95'][0]:.5f}, {v['lam_ci95'][1]:.5f}] | {v['sigma_A']:.3f} | {v['chaotic']} | `{f}` |")
    # 7 NM
    import s2_eval
    L += ["", "## 7. Nelder–Mead (stage-2 item 3)", "", src_of(s2_eval.nm_gen, "adapt_physics/stage2/scripts/s2_eval.py"),
          quote("adapt_physics/stage2/scripts/s2_eval.py", r"P, _ = nelder_mead_batched", 0, 0),
          f"Frozen: {s2['part_B']['item3_two_parameter']['H']}", ""]
    # 8 hardware
    gpus = sh("nvidia-smi", "--query-gpu=name,memory.total", "--format=csv,noheader")
    import os
    tot = {}
    for jf in (PKG / "pivot" / "jobs.state.json", PKG / "stage2" / "jobs.state.json"):
        if jf.exists():
            for k, v in json.loads(jf.read_text()).items():
                if "end" in v:
                    tot[jf.parent.name] = tot.get(jf.parent.name, 0) + (v["end"] - v["start"]) / 3600
    tr_h = sum(json.loads(d.read_text())["train_seconds"] for d in (config.RUNS / "train").glob("*/info.json")) / 3600
    L += ["## 8. Hardware and wall-clock", "",
          f"- **Host:** {platform.node()}, {os.cpu_count()} CPU threads, {platform.platform()}.",
          f"- **GPUs:** {'; '.join(gpus.splitlines())}. These are shared: up to 3 jobs per GPU in stage 2.",
          f"- **Software:** Python {platform.python_version()}, torch {torch.__version__}.",
          f"- **Training wall-clock**, summed over all models (`runs/train/*/info.json`): {tr_h:.1f} h.",
          "- **Queued job wall-clock**, summed over jobs (`jobs.state.json`): "
          + ", ".join(f"{k}: {v:.1f} h" for k, v in tot.items()) + ". Jobs overlapped, so these are not elapsed time.",
          "- **Per-state online cost** of each arm: NUMBERS APVC / APSC.", ""]
    (OUT / "paper_facts.md").write_text("\n".join(L) + "\n")
    print("wrote paper_facts.md", len(L), "lines")


def numbers():
    r = subprocess.run([sys.executable, str(PKG / "scripts" / "make_numbers_ap.py")], cwd=PKG, capture_output=True, text=True)
    ok = r.returncode == 0
    # negative test: a duplicate section must raise NumbersError
    sys.path.insert(0, str(REPO / "tokens_horizon" / "scripts"))
    import make_numbers as MN
    neg = "not run"
    try:
        MN.SECTIONS.append("APS_NEGTEST")
        MN.table([], "APS_NEGTEST", "negative test", PKG / "stage2" / "results" / "s2_rows.csv", ["world"], [{"world": 1, "label": "x"}], "sha")
        neg = "FAILED (no error raised)"
    except MN.NumbersError as e:
        neg = f"passed (raised NumbersError: {e})"
    txt = (PKG / "NUMBERS.md").read_text()
    secs = re.split(r"(?m)^## ", txt)
    pref = ("AP",)                                   # every Adapt-the-Physics section: stage 1, pivot, stage 2, objections
    keep = ["## " + s for s in secs if s.startswith(pref)]
    rows = sum(1 for s in keep for l in s.splitlines() if l.startswith(tuple("| " + p for p in pref)))
    head = sh("git", "rev-parse", "--short", "HEAD")
    L = ["# Adapt the Physics: NUMBERS (every AP section: stage 1 AP*, pivot APV*, stage 2 APS*, objections APDD*/APFR*/APEDGE*)", "",
         f"Copied from `adapt_physics/NUMBERS.md` at `{head}` by `adapt_physics/stage2/scripts/s2_paper_facts.py numbers`.", "",
         "**Checker status:**",
         f"- Fresh build (`scripts/make_numbers_ap.py`, strict tokens-horizon checker with the AP extension): "
         f"{'passed' if ok else 'FAILED: ' + r.stderr[-400:]}. {r.stdout.strip()}.",
         f"- Negative test (a duplicate section code must raise): {neg}.",
         f"- Rows in these sections: {rows}.", ""] + keep
    (OUT / "numbers_export.md").write_text("\n".join(L) + "\n")
    print("numbers export", "ok" if ok else "FAILED", rows, "rows;", neg)


if __name__ == "__main__":
    {"facts": facts, "numbers": numbers}[sys.argv[1]]()
